### ISSUE TITLE
【obniz】Node-REDで実行していると処理が止まらなくなる 

### ISSUE THREAD

**Issue by kamakurakae** [obniz/obniz-nodered-sdk#7]
TwitterのDMで問い合わせいたしました、鎌倉と申します。（@kk_puruzera）（kae.kamakura.76@gmail.com）

Node-REDとobnizを繋いで動きの確認をしていると以下の事象が発生します。
色々と調べましたが原因が特定できずにいます。
お手数ですが、ご確認のほどよろしくお願いいたします。
足りない情報がありましたらご連絡ください。

【事象】
処理が停止しない。（obniz初期画面（QRコード画面）に戻らない）

【状況】
・obniz処理停止用のノードを実行しても止まらない。
処理停止用のノードは下記折りたたみ内に書き出したjsonを貼り付けていますのでご確認ください。

<details><summary>jsonコード</summary>

```json
[
    {
        "id": "bf623683.7ad178",
        "type": "debug",
        "z": "bdefa951.412b28",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 590,
        "y": 80,
        "wires": []
    },
    {
        "id": "e058fe5.e0769",
        "type": "obniz-function",
        "z": "bdefa951.412b28",
        "obniz": "",
        "name": "",
        "code": "msg.payload = \"finish\";\nawait obniz.wait(1000); \nobniz.close();\n\nreturn msg;",
        "x": 420,
        "y": 80,
        "wires": [
            [
                "bf623683.7ad178"
            ]
        ]
    },
    {
        "id": "b6a2420f.d4a57",
        "type": "inject",
        "z": "bdefa951.412b28",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 240,
        "y": 80,
        "wires": [
            [
                "e058fe5.e0769"
            ]
        ]
    }
]
```
</details>

・すべてのノード、フローを無効化しても止まらない。
下図のような状態でも処理が止まらない時があります。
![image](https://user-images.githubusercontent.com/91707987/159636962-0586557e-7501-4aee-bb59-7126b667c150.png)

・Node-REDのChromeタブを閉じても止まらない。
・Herokuを閉じても止まらない。
・Chromeを閉じても止まらない。

・obnizの電源を物理的に抜いても状況が変わらない。
obnizの電源を抜く
→しばらく待つ
→再び電源を入れる
→一瞬初期画面になる
→何らかの処理が動いているであろう画面になる

・Heroku上のコンテナを再起動しても解消しない。
（アプリOverview画面の右上「More」から「Restart all dynos」を選択）
電源OFFの動作と同様、一瞬初期画面が表示された後は何らかの処理が動いているであろう画面になります。

・処理を停止し、初期画面になったことを確認しobnizの電源を入れたままにしておくと、処理が勝手に動き出す。
Node-REDは一度ログアウトした状態になっているが、処理は動きだしている。
対象のフローは有効となっている。

・obnizを変えても発生する。

**Comment by 9wick** [comment]
@kamakurakae 


現象から予測すると、obnizの設定を削除していないのではないでしょうか。
Herokuを再起動でも再度利用される、ということからメモリ上の何かではなく、設定自体が残ってしまっているのではないかと思います。

「新規にobnizノードの設定を追加」をすると裏でobnizデバイスとの接続を確立して待機状態になります。

<img width="659" alt="スクリーンショット 2022-03-24 22 45 16" src="https://user-images.githubusercontent.com/1738049/159929763-8523fe3d-6561-453c-addd-0e5da249885b.png">

こちらの「obnizノード」を削除すると切断されると思います。
（フローの表に出てこないので少々わかりにくいかもしれません）

obniz-functionノードを開く
→ obnizデバイスを選んで右側の編集ボタン
→ 左上にある削除ボタン

にて「obnizノード」の削除ができますので、削除してデプロイを試していただけないでしょうか。


また、それでもだめな場合の暫定対処法も記載しておきます

- obnizIDのところに適当な文字を入れてデプロイしてみる
- obniz開発者コンソールよりアクセストークンを設定する、もしくは更新する
